select
	 b.MIS_DATE
	,b.[@ID]
	,b.BRANCH_CO_MNE
	,b.ARRANGEMENT_ID
	,b.CURRENCY
	,b.OR_TOTAL_AMOUNT
	,isnull(b.OR_TOTAL_AMT_LCY,b.OR_TOTAL_AMOUNT) as OR_TOTAL_AMT_LCY
	,b.DELIN_OS_AMT
	,isnull(b.DELIN_OS_AMT_LCY,b.DELIN_OS_AMT) as DELIN_OS_AMT_LCY
	,b.OS_TOTAL_AMOUNT
	,isnull(b.OS_TOTAL_AMT_LCY,b.OS_TOTAL_AMOUNT) as OS_TOTAL_AMT_LCY
from 
	bs.AA_BILL_DETAILS b 
--where b.MIS_DATE = ?
