select 
	C.MIS_DATE,
	c.BRANCH_CO_MNE
	,c.[@ID] as COLLATERAL_ID
	--,c.ETL_COLLATERAL_RIGHT
	,left(c.ETL_COLLATERAL_RIGHT,CHARINDEX('.',c.ETL_COLLATERAL_RIGHT)-1) as PROVIDER_CUSTOMER
	,case
		when r.CUSTOMER is null
		then left(c.ETL_COLLATERAL_RIGHT,CHARINDEX('.',c.ETL_COLLATERAL_RIGHT)-1)
		else r.CUSTOMER
	end as BENEFICIARY_CUSTOMER
	,r.LIMIT_REFERENCE
	,c.NOMINAL_VALUE
	,c.MAXIMUM_VALUE
	,c.EXECUTION_VALUE
	,
from
	bs.COLLATERAL C
	left join bs.COLLATERAL_RIGHT r
		on r.MIS_DATE = c.MIS_DATE
		and r.[@ID] = c.ETL_COLLATERAL_RIGHT
	left join bs.LIMIT l
		on l.MIS_DATE = r.MIS_DATE
		and l.[@ID] = r.LIMIT_REFERENCE
--where c.MIS_DATE = '2019-05-31'
