Declare @BusinessDate Date = '2019-06-10';--?;

with Transactions as (

--Security
select 
		 [@ID] as TRANSACTION_ID
		,BRANCH_CO_MNE as BRANCH_ID
--		,NULL AS COMMISSION_TYPE
		,ISNULL([CUSTOMER_NO],'-1') as DEBIT_CUSTOMER
		,ISNULL([BROKER_NO],'-1') as CREDIT_CUSTOMER
		,MIS_DATE
		,ISNULL([TRADE_DATE],MIS_DATE) AS TRANSACTION_DATE
		,[ISSUE_DATE] AS ISSUE_DATE
		,[MATURITY_DATE] AS MATURITY_DATE
		,ISNULL([CUST_ACC_NO],'-1') as DEBIT_ACCOUNT
		,ISNULL(CAST([BR_ACC_NO] as VARCHAR(25)),'-1') as CREDIT_ACCOUNT
		,dbo.fn_getusername(INPUTTER) INPUTTER
		,dbo.fn_getusername(AUTHORISER) AUTHORISER
		,ISNULL([CU_ACCOUNT_CCY],-1) as DEBIT_ACCOUNT_CCY
		,ISNULL([BR_ACCOUNT_CCY],-1) as CREDIT_ACCOUNT_CCY
		,[CUST_NO_NOM] as DEBIT_AMT_LCY
		,[BR_NO_NOM] AS CREDIT_AMT_LCY
		,[CUST_TOT_NOM] AS DEBIT_AMT_FCY
		,[BR_TOT_NOM] AS CREDIT_AMT_FCY
		,NULL as MKTG_EXCH_PROFIT 
	 
	 

from [InsightLanding].[BS].[SEC_TRADE] A
where A.MIS_DATE=@BusinessDate

union

--Data Capture
SELECT   DISTINCT
		 [@ID] as TRANSACTION_ID
		,BRANCH_CO_MNE as BRANCH_ID
		--,NULL as COMMISSION_TYPE
		,CASE WHEN SIGN='D' THEN ISNULL([CUSTOMER_ID],'-1') ELSE '-1' END  as DEBIT_CUSTOMER
		,CASE WHEN SIGN='C' THEN ISNULL([CUSTOMER_ID],'-1') ELSE '-1' END  as CREDIT_CUSTOMER
		,MIS_DATE
		,ISNULL([VALUE_DATE], MIS_DATE) AS TRANSACTION_DATE
		,NULL AS ISSUE_DATE
		,NULL AS MATURITY_DATE
		,CASE WHEN SIGN='D' THEN ISNULL(CAST([ACCOUNT_NUMBER] as VARCHAR(25)),'-1') ELSE '-1' END as DEBIT_ACCOUNT
		,CASE WHEN SIGN='C' THEN ISNULL(CAST([ACCOUNT_NUMBER] as VARCHAR(25)),'-1') ELSE '-1' END as CREDIT_ACCOUNT
		,dbo.fn_getusername(INPUTTER) INPUTTER
		,dbo.fn_getusername(AUTHORISER) AUTHORISER
		,CASE WHEN SIGN='D' THEN ISNULL([CURRENCY],'-1') ELSE '-1' END as DEBIT_ACCOUNT_CCY
		,CASE WHEN SIGN='C' THEN ISNULL([CURRENCY],'-1') ELSE '-1' END as CREDIT_ACCOUNT_CCY
		,CASE WHEN SIGN='D' THEN [AMOUNT_LCY] END as DEBIT_AMT_LCY
		,CASE WHEN SIGN='C' THEN [AMOUNT_LCY] END as CREDIT_AMT_LCY
		,CASE WHEN SIGN='D' THEN [AMOUNT_FCY] END as DEBIT_AMT_FCY
		,CASE WHEN SIGN='C' THEN [AMOUNT_FCY] END as CREDIT_AMT_FCY
		,NULL as MKTG_EXCH_PROFIT
	   

FROM [InsightLanding].[BS].[DATA_CAPTURE] D
where D.MIS_DATE=@BusinessDate


union

--FT
SELECT   DISTINCT
		 [@ID] as TRANSACTION_ID
		,BRANCH_CO_MNE as BRANCH_ID
		--,COMMISSION_TYPE
		,ISNULL(DEBIT_CUSTOMER, '-1') DEBIT_CUSTOMER
		,ISNULL(CREDIT_CUSTOMER, '-1') CREDIT_CUSTOMER
		,ISNULL([PROCESSING_DATE],MIS_DATE) MIS_DATE
		,ISNULL([PROCESSING_DATE],MIS_DATE) AS TRANSACTION_DATE
		,NULL AS ISSUE_DATE
		,NULL AS MATURITY_DATE
		,ISNULL([DEBIT_ACCT_NO], '-1') AS DEBIT_ACCOUNT
		,ISNULL([CREDIT_ACCT_NO], '-1') as CREDIT_ACCOUNT
		,dbo.fn_getusername(INPUTTER) INPUTTER
		,dbo.fn_getusername(AUTHORISER) AUTHORISER
		,ISNULL([DEBIT_CURRENCY],'-1') as DEBIT_ACCOUNT_CURRENCY
		,ISNULL([CREDIT_CURRENCY],'-1') as CREDIT_ACCOUNT_CURRENCY
		,[LOC_AMT_DEBITED] as DEBIT_AMT_LCY
		,[LOC_AMT_CREDITED] as CREDIT_AMT_LCY
		,CAST(SUBSTRING([AMOUNT_DEBITED],4,20) as DECIMAL(19,2)) as DEBIT_AMT_FCY
		,CAST(SUBSTRING([AMOUNT_CREDITED],4,20) as DECIMAL(19,2)) as CREDIT_AMT_FCY
	    ,FT.MKTG_EXCH_PROFIT


  FROM [InsightLanding].[BS].[FUNDS_TRANSFER] FT
  where FT.PROCESSING_DATE=@BusinessDate

  union

--Teller
  select DISTINCT
		 [@ID] as TRANSACTION_ID
		,BRANCH_CO_MNE as BRANCH_ID
		--,NULL AS COMMISSION_TYPE
		,ISNULL(CUSTOMER_1, '-1') as DEBIT_CUSTOMER
		,ISNULL(CUSTOMER_2, '-1') as CREDIT_CUSTOMER
		,MIS_DATE
		,ISNULL([AUTH_DATE], MIS_DATE) AS TRANSACTION_DATE
		,[VALUE_DATE_1] AS ISSUE_DATE
		,[VALUE_DATE_2] AS MATURITY_DATE
		,ISNULL([ACCOUNT_1], '-1') AS DEBIT_ACCOUNT
		,ISNULL([ACCOUNT_2], '-1') AS CREDIT_ACCOUNT
		,dbo.fn_getusername(INPUTTER) INPUTTER
		,dbo.fn_getusername(AUTHORISER) AUTHORISER
		,ISNULL([CURRENCY_1],'-1') as DEBIT_ACCOUNT_CURRENCY
		,ISNULL([CURRENCY_2],'-1') as CREDIT_ACCOUNT_CURRENCY
		,[AMOUNT_LOCAL_1] as DEBIT_AMT_LCY
		,[AMOUNT_LOCAL_2] as CREDIT_AMT_LCY
		,[AMOUNT_FCY_1] as DEBIT_AMT_FCY
		,[AMOUNT_FCY_2] as CREDIT_AMT_FCY
		,t.MKT_EXCH_PROFIT MKTG_EXCH_PROFIT

		 
	   from [InsightLanding].[BS].TELLER t
       where t.MIS_DATE=@BusinessDate

/*
	   union

--Activities (Already taken in Fact_Acct_Entries)
  select DISTINCT
		 CONCAT(AA.[@ID], '-', ST.CRF_TYPE) as TRANSACTION_ID
		,AA.BRANCH_CO_MNE as BRANCH_ID
		,CASE WHEN ETL_DR_CR='Debit' THEN ISNULL(ST.CUSTOMER_ID,'-1') ELSE '-1' END as DEBIT_CUSTOMER
		,CASE WHEN ETL_DR_CR='Credit' THEN ISNULL(ST.CUSTOMER_ID,'-1') ELSE '-1' END as CREDIT_CUSTOMER
		,AA.EFFECTIVE_DATE as MIS_DATE
		,AA.EFFECTIVE_DATE AS TRANSACTION_DATE
		,NULL AS ISSUE_DATE
		,NULL AS MATURITY_DATE
		,CASE WHEN ETL_DR_CR='Debit' THEN ISNULL(ST.ACCOUNT_NUMBER,'-1') ELSE '-1' END AS DEBIT_ACCOUNT
		,CASE WHEN ETL_DR_CR='Credit' THEN ISNULL(ST.ACCOUNT_NUMBER,'-1') ELSE '-1' END AS CREDIT_ACCOUNT
		,dbo.fn_getusername(ST.INPUTTER) INPUTTER
		,dbo.fn_getusername(ST.AUTHORISER) AUTHORISER
		,CASE WHEN ETL_DR_CR='Debit' THEN ST.CURRENCY ELSE '-1' END as DEBIT_ACCOUNT_CURRENCY
		,CASE WHEN ETL_DR_CR='Credit' THEN ST.CURRENCY ELSE '-1' END as CREDIT_ACCOUNT_CURRENCY
		,CASE WHEN ETL_DR_CR='Debit' THEN ST.AMOUNT_LCY END as DEBIT_AMT_LCY
		,CASE WHEN ETL_DR_CR='Credit' THEN ST.AMOUNT_LCY END as CREDIT_AMT_LCY
		,CASE WHEN ETL_DR_CR='Debit' THEN ST.AMOUNT_FCY END as DEBIT_AMT_FCY
		,CASE WHEN ETL_DR_CR='Credit' THEN ST.AMOUNT_FCY END as CREDIT_AMT_FCY		

		 
	    from BS.AA_ARRANGEMENT_ACTIVITY AA 
			inner join bs.STMT_ENTRY ST on AA.[@ID]=ST.TRANS_REFERENCE
		where	AA.EFFECTIVE_DATE = @businessdate

*/
	   union


		--Forex
Select  
		 F.[@Id] as TRANSACTION_ID
		,F.BRANCH_CO_MNE as BRANCH_ID
		--,NULL AS COMMISSION_TYPE
		,ISNULL(F.COUNTERPARTY,'-1') as DEBIT_CUSTOMER
		,'-1' as CREDIT_CUSTOMER
		,F.DEAL_DATE MIS_DATE
		,F.DEAL_DATE TRANSACTION_DATE 
		,NULL as ISSUE_DATE
		,NULL as MATURITY_DATE
		,ISNULL(F.OUR_ACCOUNT_PAY,'-1') as DEBIT_ACCOUNT
		,ISNULL(F.OUR_ACCOUNT_REC,'-1') as CREDIT_ACCOUNT
		,dbo.fn_getusername(F.INPUTTER) INPUTTER
		,dbo.fn_getusername(F.AUTHORISER) AUTHORISER
		,ISNULL(F.CURRENCY_BOUGHT,'-1') as DEBIT_ACCOUNT_CURRENCY
		,ISNULL(F.CURRENCY_SOLD,'-1') as CREDIT_ACCOUNT_CURRENCY
		,F.BUY_LCY_EQUIV as DEBIT_AMT_LCY
		,F.SEL_LCY_EQUIV as CREDIT_AMT_LCY
		,F.AMOUNT_BOUGHT as DEBIT_AMT_FCY
		,F.AMOUNT_SOLD as CREDIT_AMT_FCY
		,NULL as MKTG_EXCH_PROFIT

	From
		 (select [@ID], BRANCH_CO_MNE, COUNTERPARTY, DEAL_DATE, OUR_ACCOUNT_PAY, OUR_ACCOUNT_REC, 
		 dbo.fn_getusername(INPUTTER) as INPUTTER, 
		 dbo.fn_getusername(AUTHORISER) as AUTHORISER, 
		 CURRENCY_BOUGHT, CURRENCY_SOLD, BUY_LCY_EQUIV, SEL_LCY_EQUIV, AMOUNT_BOUGHT, AMOUNT_SOLD,
             ROW_NUMBER() over (partition by [@ID] ORDER BY DATE_TIME DESC) as MAX_ID
      from Bs.Forex) F
	where f.DEAL_DATE = @Businessdate
	and MAX_ID=1

	   union


		--Standing Order
Select  
		 cast(SO.[@Id] as nvarchar(50)) as TRANSACTION_ID
		,SO.BRANCH_CO_MNE as BRANCH_ID
		--,SO.COMMISSION_TYPE
		,ISNULL(SO.DEBIT_CUSTOMER,'-1') as DEBIT_CUSTOMER
		,ISNULL(SO.CREDIT_CUSTOMER,'-1') as CREDIT_CUSTOMER
		,SO.MIS_DATE 
		,NULL as TRANSACTION_DATE 
		,NULL as ISSUE_DATE
		,NULL as MATURITY_DATE
		,isnull(cast(CASE WHEN TYPE='BI' THEN SO.CPTY_ACCT_NO ELSE SUBSTRING(cast(SO.[@Id] AS NVARCHAR(25)),1,CHARINDEX('.', cast(SO.[@Id] AS NVARCHAR(25)))-1) END as nvarchar(25)),'-1') DEBIT_ACCOUNT
		,ISNULL(cast(SO.CPTY_ACCT_NO as nvarchar(25)),'-1') as  CREDIT_ACCOUNT
		,dbo.fn_getusername(SO.INPUTTER) INPUTTER
		,dbo.fn_getusername(SO.AUTHORISER) AUTHORISER
		,ISNULL(SO.CURRENCY,'-1') as DEBIT_ACCOUNT_CURRENCY
		,ISNULL(SO.CURRENCY,'-1') as CREDIT_ACCOUNT_CURRENCY
		,SO.CURRENT_AMOUNT_BAL as DEBIT_AMT_LCY
		,SO.CURRENT_AMOUNT_BAL as CREDIT_AMT_LCY
		,SO.CURRENT_AMOUNT_BAL as DEBIT_AMT_FCY
		,SO.CURRENT_AMOUNT_BAL as CREDIT_AMT_FCY
		,NULL as MKTG_EXCH_PROFIT 

	From
		 [BS].[STANDING_ORDER] SO
	where SO.MIS_DATE = @Businessdate

	
	union

		--Charges
Select  
		 CH.[@Id] as TRANSACTION_ID
		,CH.BRANCH_CO_MNE as BRANCH_ID
		--,CH.CHARGE_CODE
		,ISNULL(CH.CUSTOMER_NO,'-1') as DEBIT_CUSTOMER
		,'-1' as CREDIT_CUSTOMER
		,CH.MIS_DATE 
		,CH.CHARGE_DATE as TRANSACTION_DATE 
		,NULL as ISSUE_DATE
		,NULL as MATURITY_DATE
		,isnull(CAST(CH.DEBIT_ACCOUNT as nvarchar(30)),'-1') DEBIT_ACCOUNT
		,'-1' as  CREDIT_ACCOUNT
		,dbo.fn_getusername(CH.INPUTTER) INPUTTER
		,dbo.fn_getusername(CH.AUTHORISER) AUTHORISER
		,ISNULL(CH.CHARGE_CCY,'-1') as DEBIT_ACCOUNT_CURRENCY
		,'-1' as CREDIT_ACCOUNT_CURRENCY
		,CH.CHARGE_AMOUNT as DEBIT_AMT_LCY
		,0 as CREDIT_AMT_LCY
		,CH.TOTAL_CHG_AMT as DEBIT_AMT_FCY
		,0 as CREDIT_AMT_FCY
		,NULL as MKTG_EXCH_PROFIT

	From
		 BS.AC_CHARGE_REQUEST CH
	where CH.CHARGE_DATE = @Businessdate
		
	
  ) 

  
  select 
		 TRANSACTION_ID
		,BRANCH_ID
		--,isnull(COMMISSION_TYPE,'-1') as COMMISSION_TYPE
		--,CASE WHEN COMMISSION_TYPE is null then '-1' else DEBIT_ACCOUNT_CCY end as COMMISSION_TYPE_CURRENCY
		,DEBIT_CUSTOMER
		,CREDIT_CUSTOMER
		,MIS_DATE
		,TRANSACTION_DATE
		,ISSUE_DATE
		,MATURITY_DATE
		,DEBIT_ACCOUNT
		,CREDIT_ACCOUNT
		,INPUTTER
		,AUTHORISER
		,DEBIT_ACCOUNT_CCY
		,CREDIT_ACCOUNT_CCY
		,DEBIT_AMT_LCY
		,CREDIT_AMT_LCY
		,DEBIT_AMT_FCY
		,CREDIT_AMT_FCY
		,MKTG_EXCH_PROFIT

  from Transactions

